# Generated by Django 4.1.7 on 2023-03-28 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(max_length=10, unique=True)),
                ('vehicle_type', models.CharField(choices=[('motorcycle', 'motorcycle'), ('car', 'car'), ('van', 'van')], max_length=12)),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Spot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spot_type', models.CharField(choices=[('motorcycle', 'motorcycle'), ('car', 'car'), ('van', 'van')], db_index=True, max_length=12)),
                ('pos', models.PositiveIntegerField(help_text="The spot's position in the row.", verbose_name='Position in row')),
                ('unocc_adj_left', models.PositiveSmallIntegerField(default=1, help_text='The number of unoccupied adjacent parking spots to the left of this spot, currently between 0 and 1 (inclusive).', verbose_name='Unoccupied adjacent spots to the left')),
                ('unocc_adj_right', models.PositiveSmallIntegerField(default=1, verbose_name='Unoccupied adjacent spots to the right')),
                ('parking_lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spots', related_query_name='spot', to='api.parkinglot')),
                ('vehicle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spots', related_query_name='spot', to='api.vehicle')),
            ],
            options={
                'ordering': ['parking_lot_id', 'pos'],
            },
        ),
    ]
